#!/usr/bin/env python3
"""Phase 0 — render docs/phase0-scope.md from scope-classified.json.

Sub-classifies the "hand-coded" (no grammar.xml) bucket into three effort tiers, because
they are very different amounts of Phase 1 work:
  - spelling   : Morfologik / hunspell speller rules -> Phase 1.1 (FSA reader) covers these
  - data-replace: SimpleReplace-style rules backed by a .txt list -> cheap, data-driven
  - java       : genuine hand-coded Java rule logic -> Phase 1.5, ported individually
XML-pattern rules are Phase 1.4.
"""
import json
import os
import re

SPELLING = re.compile(r"(MORFOLOGIK_RULE|_SPELLER_RULE|SPELLING_RULE)")
DATA_REPLACE = re.compile(r"SIMPLE_REPLACE")


def tier(rule):
    if rule["kind"] == "xml":
        return "xml"
    rid = rule["id"]
    if SPELLING.search(rid):
        return "spelling"
    if DATA_REPLACE.search(rid):
        return "data-replace"
    return "java"


TIER_LABEL = {
    "xml": "XML pattern (Phase 1.4)",
    "spelling": "Spelling / Morfologik (Phase 1.1)",
    "data-replace": "Data-driven replace / .txt (cheap)",
    "java": "Hand-coded Java (Phase 1.5)",
}


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "scope-classified.json")) as f:
        scope = json.load(f)

    out_dir = os.path.normpath(os.path.join(here, "..", "..", "docs"))
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "phase0-scope.md")

    cfg = scope["config"]
    lines = []
    w = lines.append

    w("# Phase 0 — Target rule scope\n")
    w("> Generated by `tools/phase0/build_scope_doc.py` from a differential run against "
      "bundled **LanguageTool 6.6**. Reproduce with the commands in "
      "[`tools/phase0/README.md`](../tools/phase0/README.md). This is a *seed* scope from a "
      "modest probe corpus — it lists rules the app's config can surface, ranked by how "
      "often they fired on the corpus, and is meant to be re-run and grown during Phase 3 "
      "differential testing.\n")

    w("## Request config mirrored from the app\n")
    w(f"- `level` = `{cfg['level']}`")
    w(f"- `disabledCategories` = `{', '.join(cfg['disabledCategories'])}`")
    w(f"- `disabledRules` = `{', '.join(cfg['disabledRules'])}`")
    leak = scope.get("filter_leak", [])
    w(f"- Filter honored server-side: **{'yes — no leak' if not leak else f'NO — {len(leak)} leaked'}**\n")

    # Effort roll-up across languages
    w("## Effort roll-up (distinct rules per tier, per language)\n")
    w("| Language | XML (1.4) | Spelling (1.1) | Data-replace | Java (1.5) | Total |")
    w("|---|---|---|---|---|---|")
    grand = {"xml": set(), "spelling": set(), "data-replace": set(), "java": set()}
    for lang, r in scope["languages"].items():
        counts = {"xml": 0, "spelling": 0, "data-replace": 0, "java": 0}
        for rule in r["rules"]:
            t = tier(rule)
            counts[t] += 1
            grand[t].add(rule["id"])
        w(f"| {lang} | {counts['xml']} | {counts['spelling']} | "
          f"{counts['data-replace']} | {counts['java']} | {r['distinct_rules']} |")
    w(f"| **distinct across all** | {len(grand['xml'])} | {len(grand['spelling'])} | "
      f"{len(grand['data-replace'])} | {len(grand['java'])} | "
      f"{sum(len(s) for s in grand.values())} |\n")

    w("## Language-set decisions\n")
    w("- **In scope & bundled:** en-US, en-GB, en-AU, en-CA, fr, de-DE, de-AT, de-CH, es, "
      "pt-PT, pt-BR, it, pl.")
    w("- **`nl-BE`:** appears in the app's UI language list "
      "(`projects.impl.ts`) but **no Dutch data is bundled** (no `nl` rules dir in the LT "
      "resources). Decision required: drop from the UI list, or add Dutch LT data. Not part "
      "of Phase 1 build scope either way.")
    w("- **`ca` (Catalan):** bundled in the LT data but **not** in the app's language scope "
      "— excluded from the port.\n")

    w("## Ranked target set per language\n")
    for lang, r in scope["languages"].items():
        w(f"### {lang} — {r['distinct_rules']} distinct rules, {r['total_matches']} hits\n")
        cats = ", ".join(f"`{c}` ({n})" for c, n in r["category_frequency"].items())
        w(f"Categories fired: {cats}\n")
        w("| Rank | Rule ID | Category | Hits | Tier | Sample |")
        w("|---|---|---|---|---|---|")
        for i, rule in enumerate(r["rules"], 1):
            t = tier(rule)
            sample = "; ".join(s for s in rule.get("samples", []) if s)[:40]
            sample = sample.replace("|", "\\|") or "—"
            w(f"| {i} | `{rule['id']}` | {rule['category']} | {rule['hits']} | "
              f"{TIER_LABEL[t]} | {sample} |")
        w("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
